# workflow name
name: Hello Work Workflow   

# trigger
on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - main

jobs:
  build_job:                        # 1st job name
    runs-on: ubuntu-latest          # runner

    steps:                    
      - name: Say Hello
        run: echo "Hello World!"
      - name: Say by
        run: echo "by!"        

  test_job:                         # 2nd job name
    runs-on: ubuntu-latest          # runner

    steps:                    
      - name: Say Hello
        run: echo "Hello World!"
      - name: Say by
        run: echo "by!"        
         
  deploy_job:                       # 3rd job name
    runs-on: ubuntu-latest          # runner

    steps:                    
      - name: Say Hello
        run: echo "Hello World!"
      - name: Say by
        run: echo "by!"        